/**
 * カタログ種目の英名。**ID → 英名の表。**
 *
 * 日本語名は `exerciseCatalog.ts` の `name` がそのまま基準（`docs/design-i18n.md` §4）。
 * 同じ件数ぶんをもう一度日本語で書かないために、辞書（`ja.ts` / `en.ts`）ではなく
 * ここに置く。**辞書のキーではないので、重複の検査にも掛からない**——
 * 「ケーブルカール」と「カール」のように、語が重なるのが当たり前の一覧だから。
 *
 * この表の**キーがそのまま `CatalogId`。**カタログとの突き合わせは
 * `exerciseCatalog.test.ts` が両方向で見る（足りなくても、余っても落ちる）。
 */
export const CATALOG_NAMES_EN = {
  // 胸
  ex_bench: 'Bench Press',
  ex_incline_bench: 'Incline Bench Press',
  ex_chest_press: 'Chest Press',
  ex_db_fly: 'Dumbbell Fly',
  ex_dips: 'Dips',
  ex_decline_bench: 'Decline Bench Press',
  ex_pec_fly: 'Pec Fly',
  ex_pushup: 'Push-Up',
  ex_knee_pushup: 'Knee Push-Up',
  ex_wide_pushup: 'Wide Push-Up',
  ex_decline_pushup: 'Decline Push-Up',
  ex_incline_pushup: 'Incline Push-Up',
  ex_archer_pushup: 'Archer Push-Up',
  ex_one_arm_pushup: 'One-Arm Push-Up',
  ex_pseudo_planche_pushup: 'Pseudo Planche Push-Up',
  ex_spiderman_pushup: 'Spiderman Push-Up',
  ex_clap_pushup: 'Clap Push-Up',
  ex_pullover: 'Dumbbell Pullover',
  ex_cable_crossover: 'Cable Crossover',
  ex_smith_bench: 'Smith Machine Bench Press',
  ex_smith_incline_bench: 'Smith Machine Incline Bench Press',

  // 背中
  ex_deadlift: 'Deadlift',
  ex_rack_pull: 'Rack Pull',
  ex_sumo_deadlift: 'Sumo Deadlift',
  ex_bb_row: 'Bent-Over Row',
  ex_underhand_row: 'Underhand Row',
  ex_pendlay_row: 'Pendlay Row',
  ex_lat_pulldown: 'Lat Pulldown',
  ex_parallel_pulldown: 'Neutral-Grip Lat Pulldown',
  ex_wide_pulldown: 'Wide-Grip Lat Pulldown',
  ex_underhand_pulldown: 'Underhand Lat Pulldown',
  ex_seated_row: 'Seated Row',
  ex_pullup: 'Pull-Up',
  ex_wide_pullup: 'Wide-Grip Pull-Up',
  ex_parallel_pullup: 'Neutral-Grip Pull-Up',
  ex_one_arm_row: 'One-Arm Row',
  ex_t_bar_row: 'T-Bar Row',
  ex_shrug: 'Shrug',
  ex_cable_shrug: 'Cable Shrug',
  ex_back_extension: 'Back Extension',
  ex_chinup: 'Chin-Up',
  ex_inverted_row: 'Inverted Row',
  ex_superman: 'Superman',
  ex_chest_supported_row: 'Chest-Supported Row',
  ex_straight_arm_pulldown: 'Straight-Arm Pulldown',
  ex_smith_row: 'Smith Machine Row',
  ex_smith_shrug: 'Smith Machine Shrug',
  ex_incline_row: 'Incline Row',

  // 脚
  ex_squat: 'Squat',
  ex_sumo_squat: 'Sumo Squat',
  ex_front_squat: 'Front Squat',
  ex_leg_press: 'Leg Press',
  ex_rdl: 'Romanian Deadlift',
  ex_cable_pull_through: 'Cable Pull-Through',
  ex_leg_extension: 'Leg Extension',
  ex_leg_curl: 'Leg Curl',
  ex_calf_raise: 'Calf Raise',
  ex_seated_calf_raise: 'Seated Calf Raise',
  ex_hack_squat: 'Hack Squat',
  ex_lunge: 'Lunge',
  ex_bulgarian_squat: 'Bulgarian Split Squat',
  ex_hip_thrust: 'Hip Thrust',
  ex_bw_squat: 'Bodyweight Squat',
  ex_step_up: 'Step-Up',
  ex_hip_lift: 'Glute Bridge',
  ex_nordic_curl: 'Nordic Hamstring Curl',
  ex_wall_sit: 'Wall Sit',
  ex_split_squat: 'Split Squat',
  ex_side_lunge: 'Side Lunge',
  ex_good_morning: 'Good Morning',
  ex_hip_abduction: 'Hip Abduction',
  ex_hip_adduction: 'Hip Adduction',
  ex_smith_squat: 'Smith Machine Squat',
  ex_smith_calf_raise: 'Smith Machine Calf Raise',
  ex_smith_hip_thrust: 'Smith Machine Hip Thrust',
  ex_smith_bulgarian_squat: 'Smith Machine Bulgarian Split Squat',
  ex_copenhagen_plank: 'Copenhagen Plank',

  // 肩
  ex_ohp: 'Shoulder Press',
  ex_lateral_raise: 'Lateral Raise',
  ex_rear_raise: 'Rear Delt Raise',
  ex_front_raise: 'Front Raise',
  ex_cable_lateral_raise: 'Cable Lateral Raise',
  ex_cable_rear_delt_fly: 'Cable Rear Delt Fly',
  ex_machine_rear_delt: 'Rear Delt Fly',
  ex_cable_front_raise: 'Cable Front Raise',
  ex_face_pull: 'Face Pull',
  ex_upright_row: 'Upright Row',
  ex_pike_pushup: 'Pike Push-Up',
  ex_handstand_pushup: 'Handstand Push-Up',
  ex_wall_handstand: 'Wall Handstand',
  ex_shoulder_tap: 'Shoulder Tap',
  ex_military_press: 'Military Press',
  ex_arnold_press: 'Arnold Press',
  ex_smith_ohp: 'Smith Machine Shoulder Press',

  // 腕
  ex_curl: 'Curl',
  ex_reverse_curl: 'Reverse Curl',
  ex_hammer_curl: 'Hammer Curl',
  ex_cable_curl: 'Cable Curl',
  ex_cable_hammer_curl: 'Cable Hammer Curl',
  ex_cable_reverse_curl: 'Cable Reverse Curl',
  ex_wrist_curl: 'Wrist Curl',
  ex_reverse_wrist_curl: 'Reverse Wrist Curl',
  ex_pushdown: 'Triceps Pressdown',
  ex_skull_crusher: 'Skull Crusher',
  ex_preacher_curl: 'Preacher Curl',
  ex_overhead_extension: 'Overhead Triceps Extension',
  ex_cable_overhead_extension: 'Cable Overhead Triceps Extension',
  ex_kickback: 'Triceps Kickback',
  ex_cable_kickback: 'Cable Triceps Kickback',
  ex_close_grip_bench: 'Close-Grip Bench Press',
  ex_diamond_pushup: 'Diamond Push-Up',
  ex_bench_dips: 'Bench Dips',
  ex_underhand_inverted_row: 'Underhand Inverted Row',
  ex_concentration_curl: 'Concentration Curl',
  ex_incline_curl: 'Incline Dumbbell Curl',
  ex_forearm_pronation: 'Forearm Pronation',
  ex_forearm_supination: 'Forearm Supination',

  // 体幹
  ex_hanging_leg_raise: 'Hanging Leg Raise',
  ex_cable_crunch: 'Cable Crunch',
  ex_cable_woodchop: 'Cable Woodchop',
  ex_ab_roller: 'Ab Wheel Rollout',
  ex_plank: 'Plank',
  ex_side_plank: 'Side Plank',
  ex_crunch: 'Crunch',
  ex_russian_twist: 'Russian Twist',
  ex_leg_raise: 'Leg Raise',
  ex_mountain_climber: 'Mountain Climber',
  ex_dead_bug: 'Dead Bug',
  ex_situp: 'Sit-Up',
  ex_bicycle_crunch: 'Bicycle Crunch',
  ex_pallof_press: 'Pallof Press',
  ex_reverse_crunch: 'Reverse Crunch',
  ex_knee_raise: 'Knee Raise',
  ex_v_up: 'V-Up',
  ex_toe_touch: 'Toe Touch',
  ex_flutter_kick: 'Flutter Kick',
  ex_hollow_hold: 'Hollow Hold',
  ex_bird_dog: 'Bird Dog',
  ex_dragon_flag: 'Dragon Flag',
  ex_side_bend: 'Side Bend',
  ex_ab_machine_crunch: 'Abdominal Crunch Machine',

  // 有酸素
  ex_running: 'Running',
  ex_walking: 'Walking',
  ex_cycling: 'Cycling (Outdoor)',
  ex_stationary_bike: 'Cycling (Stationary Bike)',
  ex_rowing_erg: 'Rowing Machine',
  ex_elliptical: 'Elliptical',
  ex_stair_climber: 'Stair Climber',
  ex_circuit: 'Circuit Training',
  ex_jump_rope: 'Jump Rope',
  ex_burpee: 'Burpee',
  ex_swim_free: 'Swimming (Freestyle)',
  ex_swim_breast: 'Swimming (Breaststroke)',
  ex_swim_back: 'Swimming (Backstroke)',
  ex_swim_fly: 'Swimming (Butterfly)',
  ex_water_walking: 'Water Walking',
} as const;

/** カタログ種目の ID。**この表のキーがそのまま一覧になる** */
export type CatalogId = keyof typeof CATALOG_NAMES_EN;
